import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Users.module.css'

export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await res.json();

  return {
    props: { users: data }
  }

}

const Users = ({ users }) => {
  return (
    <>
      <Head>
        <title>Test | Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Users</a>
          </h1>

          <div>
            <h1>All Users</h1>
            { users.map(user => (
              <Link href={'/users/' + user.id} key={user.id}>
                <a className={styles.single}>
                  <h3>{ user.name }</h3>
                </a>
              </Link>
            )) }
          </div>
      </main>
      </div>
    </>
  );
}

export default Users;
